name: Release Executables

on:
  workflow_run:
    workflows: ["Auto Tag"]
    types:
      - completed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: tag
        shell: bash
        run: |
          tag=$(git tag --sort=-v:refname | head -n 1)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Latest tag: $tag"

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install build-essential

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            gcc src/Koboi.c src/Lexer/Lexer.c src/Parser/Parser.c src/Compiler/SyntaxTapeS/SS.c -o Koboi-Windows.exe
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            gcc src/Koboi.c src/Lexer/Lexer.c src/Parser/Parser.c src/Compiler/SyntaxTapeS/SS.c -o Koboi-MacOS
          else
            gcc src/Koboi.c src/Lexer/Lexer.c src/Parser/Parser.c src/Compiler/SyntaxTapeS/SS.c -o Koboi-Linux
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: Koboi-${{ matrix.os }}
          path: Koboi*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Get latest tag
        id: tag
        shell: bash
        run: |
          tag=$(git tag --sort=-v:refname | head -n 1)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            artifacts/Koboi-ubuntu-latest/Koboi-Linux
            artifacts/Koboi-windows-latest/Koboi-Windows.exe
            artifacts/Koboi-macos-latest/Koboi-MacOS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
