name: Release Executables

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install build-essential

      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            gcc src/Koboi.c src/Lexer/Lexer.c -o Koboi.exe
          else
            gcc src/Koboi.c src/Lexer/Lexer.c -o Koboi
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: Koboi-${{ matrix.os }}
          path: Koboi*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/Koboi-ubuntu-latest/Koboi
            artifacts/Koboi-windows-latest/Koboi.exe
            artifacts/Koboi-macos-latest/Koboi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          